# Generated by Django 3.2.6 on 2021-10-13 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bannername', models.CharField(max_length=40)),
                ('bannerimage', models.CharField(max_length=60)),
            ],
        ),
    ]
