# Generated by Django 3.2.6 on 2021-10-19 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory_name', models.CharField(max_length=40)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.category')),
            ],
        ),
    ]
