# Generated by Django 3.2.6 on 2021-10-26 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_subcategory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='banner',
        ),
    ]
