# Generated by Django 3.2.6 on 2021-11-13 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0008_banner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='subcategory',
        ),
    ]
