# Generated by Django 3.2.6 on 2021-11-13 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0010_notification_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discounttype', models.CharField(max_length=40)),
                ('discount', models.CharField(max_length=40)),
            ],
        ),
    ]
