# Generated by Django 3.2.6 on 2021-11-26 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0015_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='productimage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pimage1', models.CharField(max_length=50)),
                ('pimage2', models.CharField(max_length=50)),
                ('pimage3', models.CharField(max_length=50)),
                ('productid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.product')),
            ],
        ),
    ]
