# Generated by Django 3.2.6 on 2021-11-30 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0016_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='productid',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='productid',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='category_id',
        ),
        migrations.DeleteModel(
            name='product',
        ),
        migrations.DeleteModel(
            name='productimage',
        ),
        migrations.DeleteModel(
            name='stock',
        ),
        migrations.DeleteModel(
            name='subcategory',
        ),
    ]
