# Generated by Django 3.2.6 on 2021-12-01 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0018_auto_20211130_0621'),
    ]

    operations = [
        migrations.DeleteModel(
            name='stock',
        ),
    ]
