# Generated by Django 3.2.6 on 2021-12-16 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0020_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='productid',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='productid',
        ),
        migrations.DeleteModel(
            name='product',
        ),
        migrations.DeleteModel(
            name='productimage',
        ),
        migrations.DeleteModel(
            name='stock',
        ),
    ]
