# Generated by Django 3.2.6 on 2021-12-23 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0024_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='file',
        ),
    ]
