# Generated by Django 3.2.6 on 2021-12-29 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0026_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='productid',
        ),
        migrations.DeleteModel(
            name='product',
        ),
        migrations.DeleteModel(
            name='stock',
        ),
    ]
