# Generated by Django 3.2.6 on 2021-12-29 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0029_auto_20211229_1250'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('desc', models.CharField(max_length=40)),
                ('color', models.CharField(max_length=40)),
                ('small', models.BooleanField()),
                ('medium', models.BooleanField()),
                ('large', models.BooleanField()),
                ('xlarge', models.BooleanField()),
                ('unitprice', models.CharField(max_length=40)),
                ('purchaseprice', models.CharField(max_length=40)),
                ('tax', models.CharField(max_length=40)),
                ('fit', models.CharField(max_length=30)),
                ('fabric', models.CharField(max_length=30)),
                ('sleeve', models.CharField(max_length=30)),
                ('pimage1', models.CharField(max_length=50)),
                ('pimage2', models.CharField(max_length=50)),
                ('pimage3', models.CharField(max_length=50)),
                ('brand_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.brand')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.category')),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.discount')),
                ('subcategory_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.subcategory')),
            ],
        ),
        migrations.CreateModel(
            name='stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.CharField(max_length=40)),
                ('productid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.product')),
            ],
        ),
    ]
