# Generated by Django 3.2.6 on 2021-12-30 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0033_alter_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='brand_id',
        ),
        migrations.AddField(
            model_name='category',
            name='brand_id',
            field=models.ManyToManyField(to='adminapp.brand'),
        ),
    ]
