# Generated by Django 3.2.6 on 2022-01-07 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0049_addtobag_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='addtobag',
        ),
    ]
