# Generated by Django 3.2.6 on 2022-01-07 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0051_addtobag'),
    ]

    operations = [
        migrations.DeleteModel(
            name='addtobag',
        ),
    ]
