# Generated by Django 3.2.6 on 2022-01-07 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0052_delete_addtobag'),
    ]

    operations = [
        migrations.CreateModel(
            name='addtobag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
                ('size', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=50)),
            ],
        ),
    ]
