# Generated by Django 3.2.6 on 2022-01-08 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0063_addtobag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customerid',
        ),
        migrations.RemoveField(
            model_name='order',
            name='name',
        ),
        migrations.DeleteModel(
            name='addtobag',
        ),
        migrations.DeleteModel(
            name='order',
        ),
    ]
