# Generated by Django 3.2.6 on 2022-01-09 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0065_addtobag'),
    ]

    operations = [
        migrations.DeleteModel(
            name='addtobag',
        ),
    ]
