# Generated by Django 3.2.6 on 2022-01-09 14:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0071_addtobag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtobag',
            name='order_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid3, editable=False, unique=True),
        ),
    ]
