# Generated by Django 3.2.6 on 2022-01-10 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0073_alter_addtobag_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='product',
            name='subcategory_id',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='productid',
        ),
        migrations.DeleteModel(
            name='addtobag',
        ),
        migrations.DeleteModel(
            name='product',
        ),
        migrations.DeleteModel(
            name='stock',
        ),
    ]
