# Generated by Django 3.2.6 on 2022-01-10 06:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_address'),
        ('adminapp', '0074_auto_20220110_0621'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=500)),
                ('color', models.CharField(max_length=40)),
                ('small', models.BooleanField()),
                ('medium', models.BooleanField()),
                ('large', models.BooleanField()),
                ('xlarge', models.BooleanField()),
                ('unitprice', models.CharField(max_length=40)),
                ('purchaseprice', models.CharField(max_length=40)),
                ('tax', models.CharField(max_length=40)),
                ('fit', models.CharField(max_length=40)),
                ('fabric', models.CharField(max_length=40)),
                ('sleeve', models.CharField(max_length=40)),
                ('pimage1', models.CharField(max_length=50)),
                ('pimage2', models.CharField(max_length=50)),
                ('pimage3', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=40)),
                ('brand_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.brand')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.category')),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.discount')),
                ('subcategory_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.subcategory')),
            ],
        ),
        migrations.CreateModel(
            name='stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.CharField(max_length=40)),
                ('productid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.product')),
            ],
        ),
        migrations.CreateModel(
            name='addtobag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('price', models.BigIntegerField()),
                ('size', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=40)),
                ('order_date', models.CharField(max_length=50)),
                ('order_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('customerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
                ('productid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.product')),
            ],
        ),
    ]
