# Generated by Django 3.2.6 on 2021-10-18 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210923_1308'),
    ]

    operations = [
        migrations.DeleteModel(
            name='login',
        ),
        migrations.DeleteModel(
            name='user',
        ),
    ]
