# Generated by Django 3.2.6 on 2021-10-18 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_login_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='login',
        ),
        migrations.DeleteModel(
            name='user',
        ),
    ]
