# Generated by Django 3.2.6 on 2022-01-07 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='address',
        ),
    ]
